from typing import Protocol, Sequence

from ..domain.dto import AggregateMetrics, CategoryBreakdownRow, FilteredSummaryResult, MonthlySummaryRow

class PresenterPort(Protocol):
    """Port describing presenter operations (output/adapters)."""
    def present_monthly_summary(self, rows: Sequence[MonthlySummaryRow]) -> None: ...
    def present_filtered_summary(self, result: FilteredSummaryResult) -> None: ...
    def present_aggregates(self, aggregates: AggregateMetrics) -> None: ...
    def present_category_breakdown(self, rows: Sequence[CategoryBreakdownRow]) -> None: ...