from typing import Protocol
import pandas as pd
from ..domain import analysis as domain_analysis

class PresenterPort(Protocol):
    """Port describing presenter operations (output/adapters)."""
    def present_monthly_summary(self, df: pd.DataFrame) -> None: ...
    def present_filtered_summary(self, df: pd.DataFrame, excluded_months: list) -> None: ...
    def present_aggregates(self, aggregates: domain_analysis.AggregateMetrics) -> None: ...
    def present_category_breakdown(self, df: pd.DataFrame) -> None: ...