from typing import Protocol, Sequence

from ..domain.value_objects import AggregateMetrics, CategoryBreakdown, FilteredSummary, MonthlySummary

class PresenterPort(Protocol):
    """Port describing presenter operations (output/adapters)."""
    def present_monthly_summary(self, rows: Sequence[MonthlySummary]) -> None: ...
    def present_filtered_summary(self, result: FilteredSummary) -> None: ...
    def present_aggregates(self, aggregates: AggregateMetrics) -> None: ...
    def present_category_breakdown(self, rows: Sequence[CategoryBreakdown]) -> None: ...